http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  user:
    paths:
      - /user
      - /user/*
serviceEndpoints:
  user-service:
    url: http://localhost:3000/user
  httpbin:
    url: 'https://httpbin.org'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  user:
    apiEndpoints:
      - user
    policies:
      - proxy:
          action:
            serviceEndpoint: user-service
            stripPath: true
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      #- key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
